name: hotaru_player
description: "hotaru video player"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  audio_video_progress_bar: ^2.0.3

  flutter_inappwebview: ^6.1.5
  screen_brightness: ^2.0.0+2
  flutter_volume_controller: ^1.3.2

  auto_orientation:
    git:
      url: https://github.com/Marco4763/auto_orientation.git
      ref: agp_compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/hotaru_player/assets/index.html

